server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waterlemon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    cache: false


mybatis:
  #实体类所在包
  type-aliases-package: com.yj2.watermelon.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:log4j2.yaml




