package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.emergency_level
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean emergencyLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.execute_status
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String executeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.create_by
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.assign_to
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String assignTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.deleted
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.stage_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String stageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.task_tag
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String taskTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.done
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean done;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.start_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.end_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.remind_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date remindTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.sort
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.like
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.star
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.deleted_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date deletedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.is_private
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean isPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.id_num
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer idNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_task.path
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_task
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.id
     *
     * @return the value of watermelon_task.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.id
     *
     * @param id the value for watermelon_task.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.project_id
     *
     * @return the value of watermelon_task.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.project_id
     *
     * @param projectId the value for watermelon_task.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.name
     *
     * @return the value of watermelon_task.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.name
     *
     * @param name the value for watermelon_task.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.emergency_level
     *
     * @return the value of watermelon_task.emergency_level
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getEmergencyLevel() {
        return emergencyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.emergency_level
     *
     * @param emergencyLevel the value for watermelon_task.emergency_level
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setEmergencyLevel(Boolean emergencyLevel) {
        this.emergencyLevel = emergencyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.execute_status
     *
     * @return the value of watermelon_task.execute_status
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getExecuteStatus() {
        return executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.execute_status
     *
     * @param executeStatus the value for watermelon_task.execute_status
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setExecuteStatus(String executeStatus) {
        this.executeStatus = executeStatus == null ? null : executeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.create_by
     *
     * @return the value of watermelon_task.create_by
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.create_by
     *
     * @param createBy the value for watermelon_task.create_by
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.create_time
     *
     * @return the value of watermelon_task.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.create_time
     *
     * @param createTime the value for watermelon_task.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.assign_to
     *
     * @return the value of watermelon_task.assign_to
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getAssignTo() {
        return assignTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.assign_to
     *
     * @param assignTo the value for watermelon_task.assign_to
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setAssignTo(String assignTo) {
        this.assignTo = assignTo == null ? null : assignTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.deleted
     *
     * @return the value of watermelon_task.deleted
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.deleted
     *
     * @param deleted the value for watermelon_task.deleted
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.stage_id
     *
     * @return the value of watermelon_task.stage_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.stage_id
     *
     * @param stageId the value for watermelon_task.stage_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setStageId(String stageId) {
        this.stageId = stageId == null ? null : stageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.task_tag
     *
     * @return the value of watermelon_task.task_tag
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getTaskTag() {
        return taskTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.task_tag
     *
     * @param taskTag the value for watermelon_task.task_tag
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setTaskTag(String taskTag) {
        this.taskTag = taskTag == null ? null : taskTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.done
     *
     * @return the value of watermelon_task.done
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.done
     *
     * @param done the value for watermelon_task.done
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setDone(Boolean done) {
        this.done = done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.start_time
     *
     * @return the value of watermelon_task.start_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.start_time
     *
     * @param startTime the value for watermelon_task.start_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.end_time
     *
     * @return the value of watermelon_task.end_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.end_time
     *
     * @param endTime the value for watermelon_task.end_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.remind_time
     *
     * @return the value of watermelon_task.remind_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getRemindTime() {
        return remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.remind_time
     *
     * @param remindTime the value for watermelon_task.remind_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setRemindTime(Date remindTime) {
        this.remindTime = remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.p_id
     *
     * @return the value of watermelon_task.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.p_id
     *
     * @param pId the value for watermelon_task.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.sort
     *
     * @return the value of watermelon_task.sort
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.sort
     *
     * @param sort the value for watermelon_task.sort
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.like
     *
     * @return the value of watermelon_task.like
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.like
     *
     * @param like the value for watermelon_task.like
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.star
     *
     * @return the value of watermelon_task.star
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.star
     *
     * @param star the value for watermelon_task.star
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.deleted_time
     *
     * @return the value of watermelon_task.deleted_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.deleted_time
     *
     * @param deletedTime the value for watermelon_task.deleted_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setDeletedTime(Date deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.is_private
     *
     * @return the value of watermelon_task.is_private
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.is_private
     *
     * @param isPrivate the value for watermelon_task.is_private
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.id_num
     *
     * @return the value of watermelon_task.id_num
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.id_num
     *
     * @param idNum the value for watermelon_task.id_num
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIdNum(Integer idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.description
     *
     * @return the value of watermelon_task.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.description
     *
     * @param description the value for watermelon_task.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_task.path
     *
     * @return the value of watermelon_task.path
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_task.path
     *
     * @param path the value for watermelon_task.path
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", name=").append(name);
        sb.append(", emergencyLevel=").append(emergencyLevel);
        sb.append(", executeStatus=").append(executeStatus);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", assignTo=").append(assignTo);
        sb.append(", deleted=").append(deleted);
        sb.append(", stageId=").append(stageId);
        sb.append(", taskTag=").append(taskTag);
        sb.append(", done=").append(done);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", remindTime=").append(remindTime);
        sb.append(", pId=").append(pId);
        sb.append(", sort=").append(sort);
        sb.append(", like=").append(like);
        sb.append(", star=").append(star);
        sb.append(", deletedTime=").append(deletedTime);
        sb.append(", isPrivate=").append(isPrivate);
        sb.append(", idNum=").append(idNum);
        sb.append(", description=").append(description);
        sb.append(", path=").append(path);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}