package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonLock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_lock.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_lock.p_value
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte pValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_lock.expire_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_lock.p_id
     *
     * @return the value of watermelon_lock.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_lock.p_id
     *
     * @param pId the value for watermelon_lock.p_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_lock.p_value
     *
     * @return the value of watermelon_lock.p_value
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_lock.p_value
     *
     * @param pValue the value for watermelon_lock.p_value
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setpValue(Byte pValue) {
        this.pValue = pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_lock.expire_time
     *
     * @return the value of watermelon_lock.expire_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_lock.expire_time
     *
     * @param expireTime the value for watermelon_lock.expire_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pId=").append(pId);
        sb.append(", pValue=").append(pValue);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}