package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonNotify implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.title
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.from_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String fromMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.to_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String toMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.is_read
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.read_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.finally_send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date finallySendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.scene
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte scene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.terminal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte terminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.from_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte fromType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_notify.send_data
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String sendData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.id
     *
     * @return the value of watermelon_notify.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.id
     *
     * @param id the value for watermelon_notify.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.title
     *
     * @return the value of watermelon_notify.title
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.title
     *
     * @param title the value for watermelon_notify.title
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.content
     *
     * @return the value of watermelon_notify.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.content
     *
     * @param content the value for watermelon_notify.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.type
     *
     * @return the value of watermelon_notify.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.type
     *
     * @param type the value for watermelon_notify.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.from_member
     *
     * @return the value of watermelon_notify.from_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getFromMember() {
        return fromMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.from_member
     *
     * @param fromMember the value for watermelon_notify.from_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setFromMember(String fromMember) {
        this.fromMember = fromMember == null ? null : fromMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.to_member
     *
     * @return the value of watermelon_notify.to_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getToMember() {
        return toMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.to_member
     *
     * @param toMember the value for watermelon_notify.to_member
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setToMember(String toMember) {
        this.toMember = toMember == null ? null : toMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.create_time
     *
     * @return the value of watermelon_notify.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.create_time
     *
     * @param createTime the value for watermelon_notify.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.is_read
     *
     * @return the value of watermelon_notify.is_read
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.is_read
     *
     * @param isRead the value for watermelon_notify.is_read
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.read_time
     *
     * @return the value of watermelon_notify.read_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.read_time
     *
     * @param readTime the value for watermelon_notify.read_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.finally_send_time
     *
     * @return the value of watermelon_notify.finally_send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getFinallySendTime() {
        return finallySendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.finally_send_time
     *
     * @param finallySendTime the value for watermelon_notify.finally_send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setFinallySendTime(Date finallySendTime) {
        this.finallySendTime = finallySendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.send_time
     *
     * @return the value of watermelon_notify.send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.send_time
     *
     * @param sendTime the value for watermelon_notify.send_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.scene
     *
     * @return the value of watermelon_notify.scene
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.scene
     *
     * @param scene the value for watermelon_notify.scene
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setScene(Byte scene) {
        this.scene = scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.terminal
     *
     * @return the value of watermelon_notify.terminal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.terminal
     *
     * @param terminal the value for watermelon_notify.terminal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setTerminal(Byte terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.from_type
     *
     * @return the value of watermelon_notify.from_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getFromType() {
        return fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.from_type
     *
     * @param fromType the value for watermelon_notify.from_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setFromType(Byte fromType) {
        this.fromType = fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.avatar
     *
     * @return the value of watermelon_notify.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.avatar
     *
     * @param avatar the value for watermelon_notify.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_notify.send_data
     *
     * @return the value of watermelon_notify.send_data
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getSendData() {
        return sendData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_notify.send_data
     *
     * @param sendData the value for watermelon_notify.send_data
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setSendData(String sendData) {
        this.sendData = sendData == null ? null : sendData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", type=").append(type);
        sb.append(", fromMember=").append(fromMember);
        sb.append(", toMember=").append(toMember);
        sb.append(", createTime=").append(createTime);
        sb.append(", isRead=").append(isRead);
        sb.append(", readTime=").append(readTime);
        sb.append(", finallySendTime=").append(finallySendTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", scene=").append(scene);
        sb.append(", terminal=").append(terminal);
        sb.append(", fromType=").append(fromType);
        sb.append(", avatar=").append(avatar);
        sb.append(", sendData=").append(sendData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}