package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonOrganization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.owner_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.is_personal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean isPersonal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.address
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_organization.area_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.id
     *
     * @return the value of watermelon_organization.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.id
     *
     * @param id the value for watermelon_organization.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.name
     *
     * @return the value of watermelon_organization.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.name
     *
     * @param name the value for watermelon_organization.name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.avatar
     *
     * @return the value of watermelon_organization.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.avatar
     *
     * @param avatar the value for watermelon_organization.avatar
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.description
     *
     * @return the value of watermelon_organization.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.description
     *
     * @param description the value for watermelon_organization.description
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.owner_id
     *
     * @return the value of watermelon_organization.owner_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.owner_id
     *
     * @param ownerId the value for watermelon_organization.owner_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.create_time
     *
     * @return the value of watermelon_organization.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.create_time
     *
     * @param createTime the value for watermelon_organization.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.is_personal
     *
     * @return the value of watermelon_organization.is_personal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getIsPersonal() {
        return isPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.is_personal
     *
     * @param isPersonal the value for watermelon_organization.is_personal
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIsPersonal(Boolean isPersonal) {
        this.isPersonal = isPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.address
     *
     * @return the value of watermelon_organization.address
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.address
     *
     * @param address the value for watermelon_organization.address
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_organization.area_id
     *
     * @return the value of watermelon_organization.area_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_organization.area_id
     *
     * @param areaId the value for watermelon_organization.area_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", avatar=").append(avatar);
        sb.append(", description=").append(description);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", createTime=").append(createTime);
        sb.append(", isPersonal=").append(isPersonal);
        sb.append(", address=").append(address);
        sb.append(", areaId=").append(areaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}