package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.cover
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.access_control_type
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer accessControlType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.white_list
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String whiteList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.order
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.deleted
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.template_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.progress
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Double progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.deleted_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date deletedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.is_private
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer isPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.open_prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer openPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.archive
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer archive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.archive_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date archiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project.description
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_project
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.id
     *
     * @return the value of watermelon_project.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.id
     *
     * @param id the value for watermelon_project.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.cover
     *
     * @return the value of watermelon_project.cover
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.cover
     *
     * @param cover the value for watermelon_project.cover
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.name
     *
     * @return the value of watermelon_project.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.name
     *
     * @param name the value for watermelon_project.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.access_control_type
     *
     * @return the value of watermelon_project.access_control_type
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getAccessControlType() {
        return accessControlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.access_control_type
     *
     * @param accessControlType the value for watermelon_project.access_control_type
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAccessControlType(Integer accessControlType) {
        this.accessControlType = accessControlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.white_list
     *
     * @return the value of watermelon_project.white_list
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getWhiteList() {
        return whiteList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.white_list
     *
     * @param whiteList the value for watermelon_project.white_list
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setWhiteList(String whiteList) {
        this.whiteList = whiteList == null ? null : whiteList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.order
     *
     * @return the value of watermelon_project.order
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.order
     *
     * @param order the value for watermelon_project.order
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.deleted
     *
     * @return the value of watermelon_project.deleted
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.deleted
     *
     * @param deleted the value for watermelon_project.deleted
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.template_id
     *
     * @return the value of watermelon_project.template_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.template_id
     *
     * @param templateId the value for watermelon_project.template_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.progress
     *
     * @return the value of watermelon_project.progress
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Double getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.progress
     *
     * @param progress the value for watermelon_project.progress
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setProgress(Double progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.create_time
     *
     * @return the value of watermelon_project.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.create_time
     *
     * @param createTime the value for watermelon_project.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.organization_id
     *
     * @return the value of watermelon_project.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.organization_id
     *
     * @param organizationId the value for watermelon_project.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.deleted_time
     *
     * @return the value of watermelon_project.deleted_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.deleted_time
     *
     * @param deletedTime the value for watermelon_project.deleted_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setDeletedTime(Date deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.is_private
     *
     * @return the value of watermelon_project.is_private
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.is_private
     *
     * @param isPrivate the value for watermelon_project.is_private
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIsPrivate(Integer isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.prefix
     *
     * @return the value of watermelon_project.prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.prefix
     *
     * @param prefix the value for watermelon_project.prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.open_prefix
     *
     * @return the value of watermelon_project.open_prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getOpenPrefix() {
        return openPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.open_prefix
     *
     * @param openPrefix the value for watermelon_project.open_prefix
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setOpenPrefix(Integer openPrefix) {
        this.openPrefix = openPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.archive
     *
     * @return the value of watermelon_project.archive
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getArchive() {
        return archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.archive
     *
     * @param archive the value for watermelon_project.archive
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setArchive(Integer archive) {
        this.archive = archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.archive_time
     *
     * @return the value of watermelon_project.archive_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getArchiveTime() {
        return archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.archive_time
     *
     * @param archiveTime the value for watermelon_project.archive_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setArchiveTime(Date archiveTime) {
        this.archiveTime = archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project.description
     *
     * @return the value of watermelon_project.description
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project.description
     *
     * @param description the value for watermelon_project.description
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cover=").append(cover);
        sb.append(", name=").append(name);
        sb.append(", accessControlType=").append(accessControlType);
        sb.append(", whiteList=").append(whiteList);
        sb.append(", order=").append(order);
        sb.append(", deleted=").append(deleted);
        sb.append(", templateId=").append(templateId);
        sb.append(", progress=").append(progress);
        sb.append(", createTime=").append(createTime);
        sb.append(", organizationId=").append(organizationId);
        sb.append(", deletedTime=").append(deletedTime);
        sb.append(", isPrivate=").append(isPrivate);
        sb.append(", prefix=").append(prefix);
        sb.append(", openPrefix=").append(openPrefix);
        sb.append(", archive=").append(archive);
        sb.append(", archiveTime=").append(archiveTime);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}