package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonProjectNode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.node
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String node;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.title
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.is_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer isMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.is_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer isAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.is_login
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer isLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_node.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_project_node
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.id
     *
     * @return the value of watermelon_project_node.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.id
     *
     * @param id the value for watermelon_project_node.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.node
     *
     * @return the value of watermelon_project_node.node
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.node
     *
     * @param node the value for watermelon_project_node.node
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.title
     *
     * @return the value of watermelon_project_node.title
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.title
     *
     * @param title the value for watermelon_project_node.title
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.is_menu
     *
     * @return the value of watermelon_project_node.is_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.is_menu
     *
     * @param isMenu the value for watermelon_project_node.is_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIsMenu(Integer isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.is_auth
     *
     * @return the value of watermelon_project_node.is_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.is_auth
     *
     * @param isAuth the value for watermelon_project_node.is_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIsAuth(Integer isAuth) {
        this.isAuth = isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.is_login
     *
     * @return the value of watermelon_project_node.is_login
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.is_login
     *
     * @param isLogin the value for watermelon_project_node.is_login
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIsLogin(Integer isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_node.create_time
     *
     * @return the value of watermelon_project_node.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_node.create_time
     *
     * @param createTime the value for watermelon_project_node.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_node
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", node=").append(node);
        sb.append(", title=").append(title);
        sb.append(", isMenu=").append(isMenu);
        sb.append(", isAuth=").append(isAuth);
        sb.append(", isLogin=").append(isLogin);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}