package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.account
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.password
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.mobile
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.real_name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.create_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.update_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.update_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.status
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.last_login_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.sex
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.avatar
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.id_card
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.area_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.address
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.email
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.department_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.role_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.position
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_member.remark
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.id
     *
     * @return the value of watermelon_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.id
     *
     * @param id the value for watermelon_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.account
     *
     * @return the value of watermelon_member.account
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.account
     *
     * @param account the value for watermelon_member.account
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.password
     *
     * @return the value of watermelon_member.password
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.password
     *
     * @param password the value for watermelon_member.password
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.name
     *
     * @return the value of watermelon_member.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.name
     *
     * @param name the value for watermelon_member.name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.mobile
     *
     * @return the value of watermelon_member.mobile
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.mobile
     *
     * @param mobile the value for watermelon_member.mobile
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.real_name
     *
     * @return the value of watermelon_member.real_name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.real_name
     *
     * @param realName the value for watermelon_member.real_name
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.create_by
     *
     * @return the value of watermelon_member.create_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.create_by
     *
     * @param createBy the value for watermelon_member.create_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.create_time
     *
     * @return the value of watermelon_member.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.create_time
     *
     * @param createTime the value for watermelon_member.create_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.update_by
     *
     * @return the value of watermelon_member.update_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.update_by
     *
     * @param updateBy the value for watermelon_member.update_by
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.update_time
     *
     * @return the value of watermelon_member.update_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.update_time
     *
     * @param updateTime the value for watermelon_member.update_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.status
     *
     * @return the value of watermelon_member.status
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.status
     *
     * @param status the value for watermelon_member.status
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.last_login_time
     *
     * @return the value of watermelon_member.last_login_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.last_login_time
     *
     * @param lastLoginTime the value for watermelon_member.last_login_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.sex
     *
     * @return the value of watermelon_member.sex
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.sex
     *
     * @param sex the value for watermelon_member.sex
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.avatar
     *
     * @return the value of watermelon_member.avatar
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.avatar
     *
     * @param avatar the value for watermelon_member.avatar
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.id_card
     *
     * @return the value of watermelon_member.id_card
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.id_card
     *
     * @param idCard the value for watermelon_member.id_card
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.area_id
     *
     * @return the value of watermelon_member.area_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.area_id
     *
     * @param areaId the value for watermelon_member.area_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.address
     *
     * @return the value of watermelon_member.address
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.address
     *
     * @param address the value for watermelon_member.address
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.email
     *
     * @return the value of watermelon_member.email
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.email
     *
     * @param email the value for watermelon_member.email
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.organization_id
     *
     * @return the value of watermelon_member.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.organization_id
     *
     * @param organizationId the value for watermelon_member.organization_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.department_id
     *
     * @return the value of watermelon_member.department_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.department_id
     *
     * @param departmentId the value for watermelon_member.department_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.role_id
     *
     * @return the value of watermelon_member.role_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.role_id
     *
     * @param roleId the value for watermelon_member.role_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.position
     *
     * @return the value of watermelon_member.position
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.position
     *
     * @param position the value for watermelon_member.position
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_member.remark
     *
     * @return the value of watermelon_member.remark
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_member.remark
     *
     * @param remark the value for watermelon_member.remark
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", realName=").append(realName);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", sex=").append(sex);
        sb.append(", avatar=").append(avatar);
        sb.append(", idCard=").append(idCard);
        sb.append(", areaId=").append(areaId);
        sb.append(", address=").append(address);
        sb.append(", email=").append(email);
        sb.append(", organizationId=").append(organizationId);
        sb.append(", departmentId=").append(departmentId);
        sb.append(", roleId=").append(roleId);
        sb.append(", position=").append(position);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}