package com.yj2.watermelon.entity;

import java.io.Serializable;

public class WatermelonUserToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.token_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer tokenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.user_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.user_name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.token
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.login_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Integer loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.client_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_user_token.login_ip
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_user_token
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.token_id
     *
     * @return the value of watermelon_user_token.token_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.token_id
     *
     * @param tokenId the value for watermelon_user_token.token_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.user_id
     *
     * @return the value of watermelon_user_token.user_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.user_id
     *
     * @param userId the value for watermelon_user_token.user_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.user_name
     *
     * @return the value of watermelon_user_token.user_name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.user_name
     *
     * @param userName the value for watermelon_user_token.user_name
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.token
     *
     * @return the value of watermelon_user_token.token
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.token
     *
     * @param token the value for watermelon_user_token.token
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.login_time
     *
     * @return the value of watermelon_user_token.login_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Integer getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.login_time
     *
     * @param loginTime the value for watermelon_user_token.login_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setLoginTime(Integer loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.client_type
     *
     * @return the value of watermelon_user_token.client_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.client_type
     *
     * @param clientType the value for watermelon_user_token.client_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_user_token.login_ip
     *
     * @return the value of watermelon_user_token.login_ip
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_user_token.login_ip
     *
     * @param loginIp the value for watermelon_user_token.login_ip
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_user_token
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tokenId=").append(tokenId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", token=").append(token);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", clientType=").append(clientType);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}