package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonProjectMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.project_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.member_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.join_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private Date joinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.is_owner
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String isOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_member.authorize
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private String authorize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_project_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.id
     *
     * @return the value of watermelon_project_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.id
     *
     * @param id the value for watermelon_project_member.id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.project_id
     *
     * @return the value of watermelon_project_member.project_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.project_id
     *
     * @param projectId the value for watermelon_project_member.project_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.member_id
     *
     * @return the value of watermelon_project_member.member_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.member_id
     *
     * @param memberId the value for watermelon_project_member.member_id
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.join_time
     *
     * @return the value of watermelon_project_member.join_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.join_time
     *
     * @param joinTime the value for watermelon_project_member.join_time
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.is_owner
     *
     * @return the value of watermelon_project_member.is_owner
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getIsOwner() {
        return isOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.is_owner
     *
     * @param isOwner the value for watermelon_project_member.is_owner
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setIsOwner(String isOwner) {
        this.isOwner = isOwner == null ? null : isOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_member.authorize
     *
     * @return the value of watermelon_project_member.authorize
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public String getAuthorize() {
        return authorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_member.authorize
     *
     * @param authorize the value for watermelon_project_member.authorize
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    public void setAuthorize(String authorize) {
        this.authorize = authorize == null ? null : authorize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", memberId=").append(memberId);
        sb.append(", joinTime=").append(joinTime);
        sb.append(", isOwner=").append(isOwner);
        sb.append(", authorize=").append(authorize);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}