package com.yj2.watermelon.entity;

import java.io.Serializable;
import java.util.Date;

public class WatermelonProjectLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.source_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.scene_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Byte sceneType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.to_member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String toMemberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.is_comment
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private Boolean isComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.icon
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watermelon_project_log.remark
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.id
     *
     * @return the value of watermelon_project_log.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.id
     *
     * @param id the value for watermelon_project_log.id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.member_id
     *
     * @return the value of watermelon_project_log.member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.member_id
     *
     * @param memberId the value for watermelon_project_log.member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.type
     *
     * @return the value of watermelon_project_log.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.type
     *
     * @param type the value for watermelon_project_log.type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.create_time
     *
     * @return the value of watermelon_project_log.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.create_time
     *
     * @param createTime the value for watermelon_project_log.create_time
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.source_id
     *
     * @return the value of watermelon_project_log.source_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.source_id
     *
     * @param sourceId the value for watermelon_project_log.source_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.scene_type
     *
     * @return the value of watermelon_project_log.scene_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Byte getSceneType() {
        return sceneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.scene_type
     *
     * @param sceneType the value for watermelon_project_log.scene_type
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setSceneType(Byte sceneType) {
        this.sceneType = sceneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.to_member_id
     *
     * @return the value of watermelon_project_log.to_member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getToMemberId() {
        return toMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.to_member_id
     *
     * @param toMemberId the value for watermelon_project_log.to_member_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setToMemberId(String toMemberId) {
        this.toMemberId = toMemberId == null ? null : toMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.is_comment
     *
     * @return the value of watermelon_project_log.is_comment
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public Boolean getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.is_comment
     *
     * @param isComment the value for watermelon_project_log.is_comment
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIsComment(Boolean isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.project_id
     *
     * @return the value of watermelon_project_log.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.project_id
     *
     * @param projectId the value for watermelon_project_log.project_id
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.icon
     *
     * @return the value of watermelon_project_log.icon
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.icon
     *
     * @param icon the value for watermelon_project_log.icon
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.content
     *
     * @return the value of watermelon_project_log.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.content
     *
     * @param content the value for watermelon_project_log.content
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watermelon_project_log.remark
     *
     * @return the value of watermelon_project_log.remark
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watermelon_project_log.remark
     *
     * @param remark the value for watermelon_project_log.remark
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", sourceId=").append(sourceId);
        sb.append(", sceneType=").append(sceneType);
        sb.append(", toMemberId=").append(toMemberId);
        sb.append(", isComment=").append(isComment);
        sb.append(", projectId=").append(projectId);
        sb.append(", icon=").append(icon);
        sb.append(", content=").append(content);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}