package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonMember;
import com.yj2.watermelon.entity.WatermelonMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    long countByExample(WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByExample(WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insert(WatermelonMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insertSelective(WatermelonMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonMember> selectByExampleWithBLOBs(WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonMember> selectByExample(WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    WatermelonMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonMember record, @Param("example") WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonMember record, @Param("example") WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") WatermelonMember record, @Param("example") WatermelonMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKey(WatermelonMember record);
}