package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectConfig;
import com.yj2.watermelon.entity.WatermelonProjectConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonProjectConfig> selectByExample(WatermelonProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonProjectConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectConfig record, @Param("example") WatermelonProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectConfig record, @Param("example") WatermelonProjectConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectConfig record);
}