package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectLog;
import com.yj2.watermelon.entity.WatermelonProjectLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonProjectLog> selectByExampleWithBLOBs(WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonProjectLog> selectByExample(WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonProjectLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectLog record, @Param("example") WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonProjectLog record, @Param("example") WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectLog record, @Param("example") WatermelonProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectLog record);
}