package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonCollection;
import com.yj2.watermelon.entity.WatermelonCollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonCollection> selectByExample(WatermelonCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonCollection selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonCollection record, @Param("example") WatermelonCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonCollection record, @Param("example") WatermelonCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonCollection record);
}