package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonLock;
import com.yj2.watermelon.entity.WatermelonLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonLock> selectByExample(WatermelonLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonLock selectByPrimaryKey(String pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonLock record, @Param("example") WatermelonLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonLock record, @Param("example") WatermelonLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_lock
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonLock record);
}