package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonSystemLog;
import com.yj2.watermelon.entity.WatermelonSystemLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonSystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonSystemLog> selectByExampleWithBLOBs(WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonSystemLog> selectByExample(WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonSystemLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonSystemLog record, @Param("example") WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonSystemLog record, @Param("example") WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonSystemLog record, @Param("example") WatermelonSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_log
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonSystemLog record);
}