package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonOrganization;
import com.yj2.watermelon.entity.WatermelonOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonOrganization> selectByExample(WatermelonOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonOrganization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonOrganization record, @Param("example") WatermelonOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonOrganization record, @Param("example") WatermelonOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_organization
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonOrganization record);
}