package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonTaskStagesTemplate;
import com.yj2.watermelon.entity.WatermelonTaskStagesTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonTaskStagesTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonTaskStagesTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonTaskStagesTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonTaskStagesTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonTaskStagesTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonTaskStagesTemplate> selectByExample(WatermelonTaskStagesTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonTaskStagesTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonTaskStagesTemplate record, @Param("example") WatermelonTaskStagesTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonTaskStagesTemplate record, @Param("example") WatermelonTaskStagesTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonTaskStagesTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages_template
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonTaskStagesTemplate record);
}