package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonNotify;
import com.yj2.watermelon.entity.WatermelonNotifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonNotify> selectByExampleWithBLOBs(WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonNotify> selectByExample(WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonNotify selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonNotify record, @Param("example") WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonNotify record, @Param("example") WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonNotify record, @Param("example") WatermelonNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_notify
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonNotify record);
}