package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectCollection;
import com.yj2.watermelon.entity.WatermelonProjectCollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonProjectCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonProjectCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonProjectCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonProjectCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonProjectCollection> selectByExample(WatermelonProjectCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonProjectCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectCollection record, @Param("example") WatermelonProjectCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectCollection record, @Param("example") WatermelonProjectCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_collection
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectCollection record);
}