package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonSystemConfig;
import com.yj2.watermelon.entity.WatermelonSystemConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonSystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonSystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonSystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonSystemConfig> selectByExample(WatermelonSystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonSystemConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonSystemConfig record, @Param("example") WatermelonSystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonSystemConfig record, @Param("example") WatermelonSystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_system_config
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonSystemConfig record);
}