package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectAuth;
import com.yj2.watermelon.entity.WatermelonProjectAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    long countByExample(WatermelonProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByExample(WatermelonProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insert(WatermelonProjectAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insertSelective(WatermelonProjectAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonProjectAuth> selectByExample(WatermelonProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    WatermelonProjectAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectAuth record, @Param("example") WatermelonProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectAuth record, @Param("example") WatermelonProjectAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_auth
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectAuth record);
}