package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonTaskStages;
import com.yj2.watermelon.entity.WatermelonTaskStagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonTaskStagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    long countByExample(WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByExample(WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insert(WatermelonTaskStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int insertSelective(WatermelonTaskStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonTaskStages> selectByExampleWithBLOBs(WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    List<WatermelonTaskStages> selectByExample(WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    WatermelonTaskStages selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonTaskStages record, @Param("example") WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonTaskStages record, @Param("example") WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByExample(@Param("record") WatermelonTaskStages record, @Param("example") WatermelonTaskStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonTaskStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonTaskStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_task_stages
     *
     * @mbg.generated Wed Jul 03 15:24:32 CST 2019
     */
    int updateByPrimaryKey(WatermelonTaskStages record);
}