package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectTemplate;
import com.yj2.watermelon.entity.WatermelonProjectTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    long countByExample(WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByExample(WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insert(WatermelonProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insertSelective(WatermelonProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonProjectTemplate> selectByExampleWithBLOBs(WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonProjectTemplate> selectByExample(WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    WatermelonProjectTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectTemplate record, @Param("example") WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WatermelonProjectTemplate record, @Param("example") WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectTemplate record, @Param("example") WatermelonProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(WatermelonProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_template
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectTemplate record);
}