package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonDepartmentMember;
import com.yj2.watermelon.entity.WatermelonDepartmentMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonDepartmentMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    long countByExample(WatermelonDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByExample(WatermelonDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insert(WatermelonDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insertSelective(WatermelonDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonDepartmentMember> selectByExample(WatermelonDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    WatermelonDepartmentMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonDepartmentMember record, @Param("example") WatermelonDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") WatermelonDepartmentMember record, @Param("example") WatermelonDepartmentMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonDepartmentMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_department_member
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKey(WatermelonDepartmentMember record);
}