package com.yj2.watermelon.mapper;

import com.yj2.watermelon.entity.WatermelonProjectMenu;
import com.yj2.watermelon.entity.WatermelonProjectMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatermelonProjectMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    long countByExample(WatermelonProjectMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByExample(WatermelonProjectMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insert(WatermelonProjectMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int insertSelective(WatermelonProjectMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    List<WatermelonProjectMenu> selectByExample(WatermelonProjectMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    WatermelonProjectMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") WatermelonProjectMenu record, @Param("example") WatermelonProjectMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") WatermelonProjectMenu record, @Param("example") WatermelonProjectMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKeySelective(WatermelonProjectMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watermelon_project_menu
     *
     * @mbg.generated Fri Jul 05 16:52:58 CST 2019
     */
    int updateByPrimaryKey(WatermelonProjectMenu record);
}